# Generated by Django 5.0.3 on 2024-03-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djp_product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='aaa', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
